
spring:
  application:
    name: testjpa
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        master:
          url: jdbc:mysql://1.12.181.39:3306/dynamic
          username: root
          password: lhDream@123
          driver-class-name: com.mysql.jdbc.Driver # 3.2.0开始支持SPI可省略此配置
        slave:
          url: jdbc:mysql://1.12.181.39:3306/dynamic2
          username: root
          password: lhDream@123
          driver-class-name: com.mysql.jdbc.Driver